name: "examples"
on: [push]

jobs:
  # make sure the action works on a clean machines without building

  ## Defaults
  test_defaults_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_deleted.txt

  test_defaults_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt

  test_defaults_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt

  test_defaults_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt

  test_defaults_mixed_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_added.txt

  test_defaults_mixed_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_deleted.txt

  ## Strict
  test_strict_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_deleted.txt
        mode: strict
        tolerance: same

  test_strict_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt
        mode: strict
        tolerance: same

  test_strict_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt
        mode: strict
        tolerance: same

  test_strict_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt
        mode: strict
        tolerance: same

  test_strict_mixed_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_added.txt
        mode: strict
        tolerance: same

  test_strict_mixed_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_deleted.txt
        mode: strict
        tolerance: same

  ## Additions
  test_additions_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_deleted.txt
        mode: addition
        tolerance: better

  test_additions_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt
        mode: addition
        tolerance: better

  test_additions_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt
        mode: addition
        tolerance: better

  test_additions_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt
        mode: addition
        tolerance: better

  test_additions_mixed_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_added.txt
        mode: addition
        tolerance: better

  test_additions_mixed_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_deleted.txt
        mode: addition
        tolerance: better

  ## Deletions
  test_deletions_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_deleted.txt
        mode: deletion
        tolerance: better

  test_deletions_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt
        mode: deletion
        tolerance: better

  test_deletions_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt
        mode: deletion
        tolerance: better

  test_deletions_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt
        mode: deletion
        tolerance: better

  test_deletions_mixed_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_added.txt
        mode: deletion
        tolerance: better

  test_deletions_mixed_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_deleted.txt
        mode: deletion
        tolerance: better

  # Tolerance (Additions)
  test_tolerance_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_deleted.txt
        mode: addition
        tolerance: worse

  test_tolerance_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt
        mode: addition
        tolerance: same

  test_tolerance_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt
        mode: addition
        tolerance: better

  test_tolerance_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt
        mode: addition
        tolerance: mixed

  test_tolerance_mixed_added:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_added.txt
        mode: addition
        tolerance: mixed-better

  test_tolerance_mixed_deleted:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_deleted.txt
        mode: addition
        tolerance: mixed-worse

  # Outputs
  test_output_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt
        mode: addition
        tolerance: better
        output: out.txt
    - run: cat out.txt

  test_output_notifs_good:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should work
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_added.txt
        mode: addition
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Works
        notify_issue: true
        notify_check: true

  test_output_notifs_bad:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Should fail
      uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_deleted.txt
        mode: addition
        token: ${{ secrets.GITHUB_TOKEN }}
        title: Fails
        notify_issue: true
        notify_check: true
