name: "examples"
on: [push]

jobs:
  # make sure the action works on a clean machines without building

  ## Basic
  test_basic_less:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_less.txt

  test_basic_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt

  test_basic_more:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_more.txt

  test_basic_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt

  test_basic_mixed_better:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_better.txt

  test_basic_mixed_worse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_worse.txt

  # Tolerance
  test_tolerance_less:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_less.txt
        tolerance: worse

  test_tolerance_same:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file3_same.txt
        tolerance: same

  test_tolerance_more:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_more.txt
        tolerance: better

  test_tolerance_mixed:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file5_mixed.txt
        tolerance: mixed

  test_tolerance_mixed_better:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file6_mixed_better.txt
        tolerance: mixed-better

  test_tolerance_mixed_worse:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file7_mixed_worse.txt
        tolerance: mixed-worse

  # Outputs
  test_output_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_more.txt
        output: out.txt
    - run: cat out.txt

  test_output_notifs_good:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file4_more.txt
        token: ${{ secrets.GITHUB }}
        notify_issue: true
        notify_check: true

  test_output_notifs_bad:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        old: fixtures/file1_basic.txt
        new: fixtures/file2_less.txt
        token: ${{ secrets.GITHUB }}
        notify_issue: true
        notify_check: true
